## Autograd

Autograd = Automatic Gradient

PyTorch 内置的 自动微分引擎，能在计算时构建“计算图”，并根据链式法则自动求梯度。

核心对象：Tensor

- 如果 requires_grad=True，PyTorch 就会追踪它的计算。
- 调用 .backward() 时，会自动计算梯度并存到 .grad 中。

其作用在于能在反向传播过程中自动求解梯度，而无需人工实现链式法则求解

In [ ]:
import torch

x = torch.tensor(2., requires_grad=True)
y = x * x + 3 * x + 1   # y = x² + 3x + 1

y.backward()         # 反向传播
print(x.grad)        # dy/dx = 2x + 3

tensor(7.)


In [ ]:
x = torch.rand(2, 2, requires_grad=True)
y = x + 2
z = y * y * 3      
out = z.mean()       

out.backward()    
print(x)
print(x.grad)     

tensor([[0.2411, 0.4691],
        [0.3778, 0.1047]], requires_grad=True)
tensor([[3.3616, 3.7036],
        [3.5666, 3.1570]])


In [13]:
x_data = torch.tensor([1.0, 2.0, 3.0])
y_data = torch.tensor([2.0, 4.0, 6.0])

# 模型参数
weight = torch.tensor([1.0], requires_grad=True)

# 前向传播
def forward(x):
    return x * weight

# 损失函数
def loss(x, y):
    y_pred = forward(x)
    return (y_pred - y) ** 2

# 计算梯度
l = torch.mean(loss(x_data, y_data))
l.backward()

print(weight.grad)  # 打印梯度

tensor([-9.3333])
