检查torch是否安装成功

In [39]:
import torch
print("PyTorch 版本：", torch.__version__)
print("CUDA 可用：", torch.cuda.is_available())

PyTorch 版本： 2.7.1+cu118
CUDA 可用： True


## 张量(Tensor)

- **张量 (Tensor)**：实质就是PyTorch定义的一种特殊的表示**多维数组**的数据结构。
  - 0 维：标量（如 3.14）
  - 1 维：向量（如 [1,2,3]）
  - 2 维：矩阵（如二维表格）
  - n 维：高维数组（如彩色图片就是 3 维：高×宽×通道）
- PyTorch 的 Tensor 类似 NumPy 的 ndarray，但额外支持：
  - 在 **GPU 上计算**（CUDA 加速）
  - 自动记录计算过程，便于 **反向传播和求梯度**
- 每个张量都有属性：
  - `shape` → 张量的维度信息
  - `dtype` → 数据类型（float32, int64 等）
  - `device` → 存放设备（CPU 或 GPU）

In [40]:
a = torch.rand((2, 3, 4))  #构建一个3维张量，shape为(2, 3, 4)
print("a:", a, "\nshape:", a.shape, "| dtype:", a.dtype, "| device:", a.device)

#将a移动到设备
if torch.cuda.is_available():
    a = a.to("cuda")
    print("device:", a.device)

a: tensor([[[0.0087, 0.6807, 0.4384, 0.2276],
         [0.4577, 0.5093, 0.8631, 0.8098],
         [0.5114, 0.0563, 0.6031, 0.1122]],

        [[0.6400, 0.7233, 0.1051, 0.1520],
         [0.0058, 0.5382, 0.2946, 0.8865],
         [0.5383, 0.0450, 0.0089, 0.4948]]]) 
shape: torch.Size([2, 3, 4]) | dtype: torch.float32 | device: cpu
device: cuda:0


### Tensor的初始化

1. 常用初始化方法：
- `torch.zeros(shape)` → 全 0
- `torch.ones(shape)` → 全 1
- `torch.full(shape, value)` → 指定数值
- `torch.rand(shape)` → [0,1) 均匀分布
- `torch.randn(shape)` → 标准正态分布
- `torch.eye(n)` → 单位矩阵
- `torch.arange(start, end, step)` → 连续整数
- `torch.linspace(start, end, steps)` → 一个范围内等间隔的序列

2. torch.xxx_like方法：

表示创建一个新的张量，它的形状shape和dtype默认与给定的tensor相同，只是填充值或初始化方式不同。例如`torch.zeros_like(x)`,`torch.ones_like(x)`

3. 从已有数组或列表创建

可以使用torch.tensor()方法，如果是numpy数组可以使用 torch.from_numpy() 

In [41]:
x = torch.arange(0, 6)
y = torch.ones_like(x, dtype=torch.float32)
z = torch.eye(3)   # 单位阵
w = torch.tensor([[1, 4, 7], [2, 5, 8], [3, 6, 9]])
t = torch.linspace(0,6,5)
x,y,z,w,t

(tensor([0, 1, 2, 3, 4, 5]),
 tensor([1., 1., 1., 1., 1., 1.]),
 tensor([[1., 0., 0.],
         [0., 1., 0.],
         [0., 0., 1.]]),
 tensor([[1, 4, 7],
         [2, 5, 8],
         [3, 6, 9]]),
 tensor([0.0000, 1.5000, 3.0000, 4.5000, 6.0000]))

### Tensor的基本运算

- 元素级运算： +, -, *, /
- 点积(仅适用于1D向量) `torch.dot(x, y)` 
- 重新组织数据形状： `tensor.reshape(shape)`
- 转置： `tensor.t()`或`tensor.T` 
- 矩阵乘法： `torch.matmul(x, y)`
- 求和、平均值、max、min： `torch.sum(x)` `torch.mean(x)` `torch.max(x)` `torch.min(x)` 


In [42]:
tensor1 = torch.tensor([[0., 1., 2.], [3., 4., 5.]])
tensor2 = torch.tensor([[1., 1., 4.], [6., 1., 4.]])
print("+: ", tensor1 + tensor2)
print("*: ", tensor1 * tensor2)
print("-: ", tensor1 - tensor2)
print("/: ", tensor1 / tensor2)

+:  tensor([[1., 2., 6.],
        [9., 5., 9.]])
*:  tensor([[ 0.,  1.,  8.],
        [18.,  4., 20.]])
-:  tensor([[-1.,  0., -2.],
        [-3.,  3.,  1.]])
/:  tensor([[0.0000, 1.0000, 0.5000],
        [0.5000, 4.0000, 1.2500]])


In [51]:
dot_tensor1 = torch.tensor([1. ,2. ,3.])
dot_tensor2 = torch.tensor([2. ,3. ,4.])
torch.dot(dot_tensor1, dot_tensor2)

tensor(20.)

In [43]:
tensor3 = tensor1.reshape(2,3)
print("tensor3: ", tensor3)


tensor3:  tensor([[0., 1., 2.],
        [3., 4., 5.]])


In [44]:
print("tensor3.T: ", tensor3.T)

tensor3.T:  tensor([[0., 3.],
        [1., 4.],
        [2., 5.]])


In [45]:
print("matmul: ", torch.matmul(tensor3, tensor3.T))

matmul:  tensor([[ 5., 14.],
        [14., 50.]])


In [ ]:
print("sum: ", torch.sum(tensor3))
print("mean: ", torch.mean(tensor3))
print("max: ", torch.max(tensor3))
print("min: ", torch.min(tensor3))
print("argmax： ", torch.argmax(tensor3))

print("mean dim0: ", torch.mean(tensor3, dim=0))
print("mean dim1: ", torch.mean(tensor3, dim=1))

sum:  tensor(15.)
mean:  tensor(2.5000)
max:  tensor(5.)
min:  tensor(0.)
argmax：  tensor(4)
mean dim0:  tensor([1.5000, 2.5000, 3.5000])
mean dim1:  tensor([1., 4.])


### Tensor的广播机制
广播是 PyTorch 在 形状不同的张量 进行运算时的一种 自动扩展机制。

它会沿着 维度为 1 或缺失的维度 自动复制数据，使两个张量形状兼容，从而完成逐元素运算。

广播的具体规则为：
- 从最后一个维度开始逐个比较两个张量的形状。
- 如果维度相同，继续比较。
- 如果某个维度不相同，但其中一个是 1，就会广播扩展。
- 否则，报错（形状不兼容）

In [47]:
# sample 1
x = torch.tensor([[1, 2, 3],
                  [4, 5, 6]])  # 形状 [2,3]
y = torch.tensor([10, 20, 30]) # 形状 [3]
print(x + y) # y沿着第0维复制成 [[10, 20, 30], [10, 20, 30]]

# sample 2
a = torch.randn(2, 3, 1)  # 形状 [2,3,1]
b = torch.randn(1, 1, 4)  # 形状 [1,1,4]
print((a + b).shape)      # [2,3,4]

tensor([[11, 22, 33],
        [14, 25, 36]])
torch.Size([2, 3, 4])
